version: '3'

services:
  mongo: 
      image: mongo
      container_name: mongo_container
      networks:
        - app_network
      ports:
        - 27017:27017
      expose:
        - 27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  app_network:
    driver: bridge